FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir kafka-python requests feedparser

COPY config.py /app/
COPY producer_api.py /app/
COPY producer_rss.py /app/
COPY consumer_to_hdfs.py /app/
COPY spark_analysis.py /app/

ENV PYTHONUNBUFFERED=1

CMD ["/bin/bash"]
